version: "3.8"

services:
  database:
    image: postgres:latest
    ports:
      - 5433:5432
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ${PWD}/initial-seeding/init-data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net
  database-mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    container_name: database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${PWD}/initial-seeding/init-data-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    networks:
      - net

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080
    restart: always
    networks:
      - net

networks:
  net:
